name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: binge
          POSTGRES_USER: viveknathani
          POSTGRES_PASSWORD: root
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2

    - name: set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
        
    - name: build
      run: make build

    - name: test
      run: make test